#!/usr/bin/env bash
# displays the visitor IP along with the HTTP status code from the Apache log file

while IFS=' ' read -r line;
	do
	echo "$line" | awk '{print $1 " " $9}'

done < ./apache-access.log;
