#!/usr/bin/env bash
# fix
# kill apache processes that takes the port 8080
# kill -9 $(ps -e | grep apache2 | awk '{print $1}')
pkill -f apache2
# change config file mode : adding writing previlige
chmod 644 /etc/nginx/nginx.conf
# update config files
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
